template-file-path: ../Compute/CreateCompute-(Standalone+ALB).yaml

parameters:
  ProjectName: kavishala
  Environment: prod
  StandaloneSubnet: subnet-0d4e5f6a7b8c90123
  StandAloneInstanceAvalilabilityZone: ap-south-1a
  InstanceName: backend-server
  ElasticIPforStandAlone: yes
  VPCName: vpc-0d4e5f6a7b8c90124
  PrivateSubnet: subnet-0d4e5f6a7b8c90125,subnet-0d4e5f6a7b8c90126
  PublicSubnet: subnet-0d4e5f6a7b8c90123,subnet-0d4e5f6a7b8c90127
  SecurityGroupForInstances: sg-0d4e5f6a7b8c90128
  CustomMetricsS3BucketName: kavishala-prod-ec2-custom-metrics
  InstanceType: m5.xlarge
  MachineType: ubuntu
  Timezone: India Standard Time
  Region: ap-south-1
  ImageIds: Pass-AMI-Manually
  ImageIdManual: ami-0f58b397bc5c1f2e8
  KeyName: kavishala-prod-key
  Tenancy: default
  DeviceBlockName: /dev/sda1
  VolumeSizeFortheDevice: 200
  DeleteVolumeOnTermination: true
  VolumeEncryption: true
  EbsOptimisation: true
  LoadBalancer: no
  LoadBalancerName: backend-prod-alb
  LoadBalancerScheme: internal
  EnableSSL: no
  ListenerCertificateArn: arn:aws:acm:ap-south-1:123456789012:certificate/b2c3d4e5-f6a7-8901-bcde-f12345678901
  ALBSecurityGroup: sg-0d4e5f6a7b8c90129

tags:
  Environment: prod
  Project: kavishala
