template-file-path: ../Database/CreateRds-ParentStack.yaml

parameters:
  Application: kavishala
  ApplicationVersion: 1
  Compliance: other
  Confidentiality: private
  CopyTagsToSnapshot: true
  CustomDBSecurityGroup: sg-0b2c3d4e5f6a78901
  CustomParameterGroupFamily: postgres17
  DBAllocatedStorage: 20
  DBAutoMajorVersionUpgrade: false
  DBAutoMinorVersionUpgrade: false
  DBBackupRetentionPeriod: 7
  DBCloudwatchLogExports: postgresql
  DBDeleteAutomatedBackups: true
  DBDeletionProtection: true
  DBEngineMode: postgres
  DBEngineVersion: 17.4
  DBInstanceClass: db.t3.medium
  DBInstanceIdentifier: postgresql-rds-dev
  DBMasterUsername: kavishaladevuser
  DBMasterUserPassword: Kv3!devPgPass2024
  DBMaxAllocatedStorage: 50
  DBMultiAZ: false
  DBName: kavishaladev
  DBPasswordCreationAndRotationFromSecretsManager: false
  DBPort: 5432
  DBStorageEncrypted: true
  DBStorageType: gp3
  EnablePerformanceInsights: false
  Environment: dev
  LicenseModel: postgresql-license
  PasswordRotationFrequencyInDays: 90
  PerformanceInsightsRetentionPeriod: 7
  PrivateSubnet1: subnet-0c3d4e5f6a7b89012
  PrivateSubnet2: subnet-0c3d4e5f6a7b89013
  ProjectCostCenter: 1
  ProjectName: kavishala
  PubliclyAccessible: false
  PublicSubnet1: subnet-0a1b2c3d4e5f67890
  PublicSubnet2: subnet-0a1b2c3d4e5f67894
  RotateImmediatelyOnUpdate: true
  S3BucketToStoreTemplates: kavishala-dev-cloudformation-templates
  VpcId: vpc-0a1b2c3d4e5f67891

tags:
  Environment: dev
  Project: kavishala
