template-file-path: ../Database/CreateRds-ParentStack.yaml

parameters:
  Application: kavishala
  ApplicationVersion: 1
  Compliance: other
  Confidentiality: private
  CopyTagsToSnapshot: true
  CustomDBSecurityGroup: sg-0e5f6a7b8c9d01234
  CustomParameterGroupFamily: postgres17
  DBAllocatedStorage: 50
  DBAutoMajorVersionUpgrade: false
  DBAutoMinorVersionUpgrade: false
  DBBackupRetentionPeriod: 7
  DBCloudwatchLogExports: postgresql
  DBDeleteAutomatedBackups: true
  DBDeletionProtection: true
  DBEngineMode: postgres
  DBEngineVersion: 17.4
  DBInstanceClass: db.r5.xlarge
  DBInstanceIdentifier: postgresql-rds-prod
  DBMasterUsername: kavishalaproduser
  DBMasterUserPassword: Kv7!prodPgPass2024
  DBMaxAllocatedStorage: 100
  DBMultiAZ: true
  DBName: kavishalaprod
  DBPasswordCreationAndRotationFromSecretsManager: false
  DBPort: 5432
  DBStorageEncrypted: true
  DBStorageType: gp3
  EnablePerformanceInsights: false
  Environment: prod
  LicenseModel: postgresql-license
  PasswordRotationFrequencyInDays: 90
  PerformanceInsightsRetentionPeriod: 7
  PrivateSubnet1: subnet-0e5f6a7b8c9d01235
  PrivateSubnet2: subnet-0e5f6a7b8c9d01236
  ProjectCostCenter: 1
  ProjectName: kavishala
  PubliclyAccessible: false
  PublicSubnet1: subnet-0d4e5f6a7b8c90123
  PublicSubnet2: subnet-0d4e5f6a7b8c90127
  RotateImmediatelyOnUpdate: true
  S3BucketToStoreTemplates: kavishala-prod-cloudformation-templates
  VpcId: vpc-0d4e5f6a7b8c90124

tags:
  Environment: prod
  Project: kavishala
