template-file-path: ./Network/CreateNetwork-1NAT.yaml

parameters: 
    ProjectName: kavishala
    Environment: prod
    NumberOfAZs: 2
    AvailabilityZones: us-east-1a,us-east-1b
    VpcCidr: 10.0.0.0/16
    VpcTenancy: default
    WantVpcFlowLogs: enable
    VpcFlowLogStorageType: S3
    PublicSubnet0Cidr: 10.0.200.0/24
    PublicSubnet1Cidr: 10.0.201.0/24
    PublicSubnet2Cidr: 10.0.202.0/24
    PublicSubnet3Cidr: 10.0.203.0/24
    PublicSubnet4Cidr: 10.0.204.0/24
    PublicSubnet5Cidr: 10.0.205.0/24
    PrivateSubnet0Cidr: 10.0.0.0/22
    PrivateSubnet1Cidr: 10.0.4.0/22
    PrivateSubnet2Cidr: 10.0.8.0/22
    PrivateSubnet3Cidr: 10.0.12.0/22
    PrivateSubnet4Cidr: 10.0.16.0/22
    PrivateSubnet5Cidr: 10.0.20.0/22
    DataSubnet0Cidr: 10.0.100.0/24
    DataSubnet1Cidr: 10.0.101.0/24
    DataSubnet2Cidr: 10.0.102.0/24
    DataSubnet3Cidr: 10.0.103.0/24
    DataSubnet4Cidr: 10.0.104.0/24
    DataSubnet5Cidr: 10.0.105.0/24
    WantDataBaseTier: yes
    WantNatGatewayForPrivateSubnets: yes
    WantNatGatewayForDataBaseSubnets: no

tags:
